  Description: { type: String, required: False ,   
  Name: { type: string, required: False ,   
  Start: { type: string, required: False ,   
  ProjectID: { type: Number, required: False ,   
  UserID: { type: Number, required: False ,   
