/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 12-led-2024 20:34:12 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS steps_stepsid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Steps" CASCADE
;

/* Create Tables */

CREATE TABLE "Steps"
(
	"Name" varchar(100) NULL,
	"ScreenSC" varchar(50) NULL,
	"StepsID" integer NOT NULL   DEFAULT NEXTVAL(('"steps_stepsid_seq"'::text)::regclass),
	"ScreenSR" varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Steps" ADD CONSTRAINT "PK_Steps"
	PRIMARY KEY ("StepsID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE steps_stepsid_seq INCREMENT 1 START 1
;